### ISSUE TITLE
Always "Exit in case user invoked program with incorrect arguments"

### ISSUE THREAD

**Issue by BontaVlad** [docopt/docopt.nim#17]
If I am using the nimble install version, docopt always returns "Usage: my_program etc", even on the examples provided. If I copy docopt.nim from the git clone version and overwrite docopt.nim in the nimble pkgs docopt-0.6.2 everything seems to work fine. I want to add that I am using nim v 0.14.3.

**Comment by BlaXpirit** [comment]
I do not intend to make a release after every change in the compiler.

Latest release supports latest release of Nim.

[devel](https://github.com/docopt/docopt.nim/tree/devel) branch might support devel branch of Nim.

**Comment by dom96** [comment]
@BontaVlad Pro-Tip: You can install the GitHub version of docopt by running ``nimble install docopt@#head`` (or depend on it in your Nimble file by specifying ``requires "docopt#head"``).
