### ISSUE TITLE
Docopt isn't thread safe - cannot use within spawn

### ISSUE THREAD

**Issue by genotrance** [docopt/docopt.nim#26]
docopt-0.6.4\docopt.nim(569, 6) Warning: 'docopt_exc' is not GC-safe as it calls 'fix' [GcUnsafe2]
docopt-0.6.4\docopt.nim(602, 6) Warning: 'docopt' is not GC-safe as it calls 'docopt_exc' [GcUnsafe2]

**Comment by genotrance** [comment]
Worked around this by passing the docopt() Table from parent to the child threads which is reasonable in my use case.

**Comment by oprypin** [comment]
¯\\\_(ツ)_/¯

**Comment by nigredo-tori** [comment]
There was my PR merged to master that made docopt `{.gcsafe.}`, but it didn't yet make it into a released version. There seems to be another problem, though: Nim's effect tracking now (in devel branch) seems to take methods into account, so all the method bases should have proper effect pragmas specified.
