### ISSUE TITLE
Please release new version

### ISSUE THREAD

**Issue by vegansk** [docopt/docopt.nim#28]
The last release doesn't work with the devel branch of the compiler, see https://github.com/nim-lang/Nim/issues/5436

**Comment by dom96** [comment]
Perhaps @docopt or @oprypin could add @vegansk as a collaborator? I'm guessing @oprypin is busy with other projects.

**Comment by oprypin** [comment]
I've said previously

> I do not intend to make a release after every change in the compiler.
> 
> Latest release supports latest release of Nim.

But oh well, who cares... I guess I can make a release.

The problem is that even latest commit seems to fail again on devel.
https://travis-ci.org/docopt/docopt.nim/jobs/216903139
