### ISSUE TITLE
docopt crashing in runtime with `devel` nim

### ISSUE THREAD

**Issue by nigredo-tori** [docopt/docopt.nim#29]
So docopt.nim is broken again after changes in `Nim`: https://travis-ci.org/docopt/docopt.nim/jobs/216903139 .

`git bisect` on Nim led me to this commit: https://github.com/nim-lang/Nim/commit/1268ca79e5436e33a9fca0999477adf8f3e937ae . The mentioned issue concerns behaviour of methods on `nil` references. It seems that previously in this case the dispatcher did nothing. This seems wrong and dangerous to me due to my background (any method could silently return a default value/nil!), but some ObjC folks might have been okay with it. Anyway, now in this case a `NilAccessError` is raised.

However a part of `docopt` turned out to be triggering this branch of execution, namely a call to `str` method inside a `==` method.

As an aside, I don't think ignoring errors for devel Nim branch in CI config is a way to go. Due to Nim's (im)maturity, plenty of people use devel branch with all the fresh fixes, features (and bugs). I understand that sometimes a build failure would be a result of some temporary bug, however quite often the changes causing it are there to stay, and need to be dealt with.

**Comment by oprypin** [comment]
Thanks for the information.

This just makes little sense, somehow reference objects are always nillable but passing that on to another method that accepts a nillable object is somehow not OK. 

For the aside: Nim just has very rare releases, that's always been a major pain point, even when I was active in the community. When working with <a particular other new language>, this is never a problem.
