### ISSUE TITLE
Remove pcre dependency

### ISSUE THREAD

**Issue by AngelEzquerra** [docopt/docopt.nim#33]
This might be hard to do but it would be nice if the PCRE dependency could be removed. On Windows this is quite inconvenient because it forces you to distribute the pcre64.dll or pcre32.dll with your compiled binary. This breaks the nice "single file executable" property of many nim programs, which for small command line utilities is quite nice.

**Comment by AngelEzquerra** [comment]
I wonder, if regular expressions are needed by docopt.nim, perhaps it could be possible to use them at compile time only? For example, perhaps docopt could generate parseopt compatible code at runtime, thus eliminating the need to have the pcre dll on the target machine?

**Comment by oprypin** [comment]
Last time I checked, there was no time to use regular expressions at compile time.
Anyhow, I'm not going to implement this.

**Comment by dom96** [comment]
If one of you is up for it, you could create a PR to use this package: https://github.com/nitely/nim-regex

Eventually this will be adopted into the stdlib though, could be a while before that happens, but once it does this problem will be fixed automatically.

**Comment by AngelEzquerra** [comment]
@oprypin , I understand, I was just thinking out loud. Would you however be willing to change the regular expression engine from PCRE to nim-regex as @dom96 suggests? That would also solve this problem.

**Comment by oprypin** [comment]
Yes. PR welcome.

**Comment by nitely** [comment]
@AngelEzquerra nim-regex doesn't support *split with captures* (https://github.com/nitely/nim-regex/issues/8), which is used by docopt. I'll try to implement it soon and let you know.

**Comment by brentp** [comment]
this is closed by #42 , #44
