### ISSUE TITLE
lock level warnings

### ISSUE THREAD

**Issue by reactormonk** [docopt/docopt.nim#4]
.nimble/pkgs/docopt-0.1.0/docopt.nim(291, 7) Warning: method has lock level <unknown>, but another method has 0 [LockLevel]
    .nimble/pkgs/docopt-0.1.0/docopt.nim(351, 7) Warning: method has lock level <unknown>, but another method has 0 [LockLevel]
    .nimble/pkgs/docopt-0.1.0/docopt.nim(385, 7) Warning: method has lock level 0, but another method has <unknown> [LockLevel]

**Comment by BlaXpirit** [comment]
I don't know what this is and how to cause it. Never seen this.

**Comment by BlaXpirit** [comment]
Rebuilt Nim. Oh, it is this a new bug in devel branch?

**Comment by BlaXpirit** [comment]
Actually, I do see it by just writing `import docopt`. Still have no idea what this means.

**Comment by BlaXpirit** [comment]
This happens because using regex sets the lock level to unknown. These are instances where one of the methods with the same name uses a regex and one doesn't. I can't even fix this, because there is no clean way to set lock level to unknown. Instead, I just silenced these.
