### ISSUE TITLE
Latest release doesn't work on Nim 0.19

### ISSUE THREAD

**Issue by ndarilek** [docopt/docopt.nim#43]
New to Nim, so I can't do a deep dive into whether or not this is a good idea. However, it looks like you released V0.6.6, then merged in a PR that makes this work on Nim v0.18 and newer.

Would it be a good idea to release V0.7 with this change? I just attempted to build something that uses this library and it failed:

```
        ... ../../../../../../home/nolan/.nimble/pkgs/docopt-0.6.6/docopt/util.nim(36, 16) template/generic instantiation from here
        ... ../../../../../../home/nolan/.choosenim/toolchains/nim-0.19.0/lib/system.nim(414, 10) Error: 'nil' is now invalid for 'string'; compile with --nilseqs:on for a migration period; usage of '==' is a user-defined error
```

Thanks.

**Comment by oprypin** [comment]
Sorry about that.
It's released now.

**Comment by ndarilek** [comment]
Great, thanks a bunch!
