### ISSUE TITLE
Is a impure library `re` used ?

### ISSUE THREAD

**Issue by jiro4989** [docopt/docopt.nim#46]
I think that docopt depends a `regex` library, not `re`.
`regex` library is library in pure Nim.
I think that you can delete a below line of README.md.

```
An impure `re` library is used.
```

https://github.com/docopt/docopt.nim/blame/master/README.md#L139

**Comment by oprypin** [comment]
Needs followup after https://github.com/docopt/docopt.nim/pull/42
