### ISSUE TITLE
Example where command line values are used

### ISSUE THREAD

**Issue by ReneSac** [docopt/docopt.nim#5]
There is no example of actually using the values, especially things like numbers, as opposed to printing them.

**Comment by BlaXpirit** [comment]
That is true. I had a hard time coming up with a good, non-contrived example. But this is definitely something that needs to be done.

**Comment by BlaXpirit** [comment]
Added some examples.

**Comment by ReneSac** [comment]
It took a bit of a while to understand because things like `ships[]` and `move` aren't declared anywhere, but then it might be overkill. Well, I would at least declare ships[]... but...
