### ISSUE TITLE
'docopt' is not GC-safe as it calls 'docopt_exc' (nim 2.0)

### ISSUE THREAD

**Issue by RokkuCode** [docopt/docopt.nim#57]
I am using the current version of docopt with nim 2.0. On compiling the following error occours:
```
/home/user/.nimble/pkgs/docopt-0.7.0/docopt.nim(608, 6) Error: 'docopt' is not GC-safe as it calls 'docopt_exc'
```

**Comment by hoijui** [comment]
Note: `choosenim update stable` now installs nim 2.0.0, so this will happen to many people quite soon.

**Comment by hoijui** [comment]
Maybe this helps:
https://github.com/nim-lang/Nim/issues/7847

**Comment by hoijui** [comment]
.. or not :/
https://github.com/docopt/docopt.nim/issues/23

**Comment by hoijui** [comment]
<s>Until the fix gets applied to upstream (this repo), you may use it from my repo in your `*.nimble` file:

```
# Until [the fix for nim 2](https://github.com/docopt/docopt.nim/pull/58) gets merged and released in upstream docopt, we use the contributors fix directly:
#requires "docopt"
requires "https://github.com/hoijui/docopt.nim#3e8130e"
```

</s>

It is now released!
(see the next message)

**Comment by oprypin** [comment]
This is now in a release. Sorry for the huge delay. Thank you for the fix.
