### ISSUE TITLE
Most tests failing under Nim v0.11, OS X

### ISSUE THREAD

**Issue by boydgreenfield** [docopt/docopt.nim#8]
`nim compile --run test/test` under OS X with Nim v0.11 (installed yesterday), errors with the following message:

```
Tests passed: 52/164
Error: execution of an external program failed
```

Notably, I don't see any compiler warnings under v0.10.2 or v0.11 – but it does appear that some breaking change is substantially affecting this module.

**Comment by BlaXpirit** [comment]
Thanks for reporting. It is some recent change, because I've been following devel.

**Comment by BlaXpirit** [comment]
Broken in https://github.com/Araq/Nim/commit/26eae7d00e73c65670775091bad8bfd796b3e1f1

**Comment by boydgreenfield** [comment]
Great thanks @BlaXpirit. Note I opened a PR because the version needs to get bumped in the .nimble file for this to install correctly.

**Comment by BlaXpirit** [comment]
Thanks again. Fixed.

I don't see a pull request though.

**Comment by boydgreenfield** [comment]
@BlaXpirit, yeah that was my bad, oops. Thanks for the fix, though!
